# Generated by Django 4.1.3 on 2023-02-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='created',
            new_name='date_creation',
        ),
    ]
