# Generated by Django 4.1.3 on 2023-02-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_created_reply_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='accept',
            new_name='reply_accept',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='text',
            new_name='reply_text',
        ),
    ]
