# Generated by Django 4.1.3 on 2023-02-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_accept_reply_reply_accept_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
    ]
